version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    environment:
      DB_HOST: ${DB_HOST}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      JWT_SECRET: ${JWT_SECRET}
      PORT: 8080
      DB_PORT: 5432
      SSL_PASSWORD: ${SSL_PASSWORD}
      SSL_ALIAS: ${SSL_ALIAS}
      SSL_KEYSTORE: ${SSL_KEYSTORE}
