version = 0.1
[default.deploy.parameters]
stack_name = "cleanCheckProd"
resolve_s3 = true
s3_prefix = "cleanCheckProd"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "DBName=\"cleancheck\" EC2InstanceType=\"t2.large\" KeyPairName=\"cleanCheck\""
image_repositories = []
disable_rollback = true
