AWSTemplateFormatVersion: 2010-09-09
Description: 'Simple Template for EC2 and RDS PostgreSQL with Secrets Manager'

Parameters:
  DBName:
    Type: String
    Default: cleancheck
  EC2InstanceType:
    Type: String
    Default: t2.small
  KeyPairName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Name of an existing EC2 KeyPair

Resources:
  # Secrets Manager for RDS credentials
  DBSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub ${AWS::StackName}-db-credentials
      GenerateSecretString:
        SecretStringTemplate: '{"username": "dbadmin"}'
        GenerateStringKey: "password"
        PasswordLength: 16
        ExcludeCharacters: '"@/\'

  # Secrets Manager for JWT Secret
  JWTSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub ${AWS::StackName}-jwt-secret
      GenerateSecretString:
        SecretStringTemplate: '{"jwt_secret_name": "myjwtsecret"}'
        GenerateStringKey: "jwt_secret"
        PasswordLength: 16
        ExcludeCharacters: '"@/\'


  # RDS Security Group
  RDSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: RDS Security Group
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          CidrIp: 0.0.0.0/0

  # RDS Instance
  RDSInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBName: !Ref DBName
      Engine: postgres
      MasterUsername: !Join ['', ['{{resolve:secretsmanager:', !Ref DBSecret, ':SecretString:username}}' ] ]
      MasterUserPassword: !Join ['', ['{{resolve:secretsmanager:', !Ref DBSecret, ':SecretString:password}}' ] ]
      DBInstanceClass: db.t3.micro
      AllocatedStorage: '5'
      VPCSecurityGroups:
        - !GetAtt RDSSecurityGroup.GroupId
      PubliclyAccessible: true

  # S3 Bucket
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Join ['', ['cleancheck-', !Ref DBName, '-', !Ref "AWS::AccountId"] ]


  # EC2 Instance Role and Profile
  EC2Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
      Policies:
        - PolicyName: S3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:ListBucket
                Resource:
                  - !GetAtt S3Bucket.Arn
                  - !Sub ${S3Bucket.Arn}/*
        - PolicyName: RDSSecretsAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource: !Ref DBSecret
        - PolicyName: JWTSecretsAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource: !Ref JWTSecret

  EC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref EC2Role

  # EC2 Security Group
  EC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: EC2 Security Group
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          CidrIp: 0.0.0.0/0

  # EC2 Instance
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref EC2InstanceType
      ImageId: ami-0866a3c8686eaeeba
      KeyName: !Ref KeyPairName
      SecurityGroupIds:
        - !Ref EC2SecurityGroup
      IamInstanceProfile: !Ref EC2InstanceProfile
      UserData:
        Fn::Base64: !Sub |
          #cloud-boothook
          #!/bin/bash 
          
          #Clone the repository
          git clone https://github.com/EmilianoChofis/Back-CleanCheck.git /home/ubuntu/Back-CleanCheck
          
          #Change directory
          cd /home/ubuntu/Back-CleanCheck
          
          #Set the directory for safe
          git config --global --add safe.directory /home/ubuntu/Back-CleanCheck
          
          #Checkout to the deploy branch
          git checkout deploy
          
          #copy the setup.sh to the home directory
          cp /home/ubuntu/Back-CleanCheck/setup.sh /home/ubuntu/
          
          #copy the docker-compose.yml to the home directory
          cp /home/ubuntu/Back-CleanCheck/docker-compose.yml /home/ubuntu/
          
          # Establish environment variables
          echo "export DB_HOST=${RDSInstance.Endpoint.Address}" | sudo tee -a /etc/environment
          echo "export DB_NAME=${DBName}" | sudo tee -a /etc/environment
          echo "export DBSecret=${DBSecret}" | sudo tee -a /etc/environment
          
          #Adding sleep 
          sleep 10
          
          # Setting up the permission for the setup.sh file
          chmod +x /home/ubuntu/setup.sh
          
          # Running the setup.sh file
          /home/ubuntu/setup.sh
Outputs:
  EC2PublicIP:
    Description: Public IP of EC2 Instance
    Value: !GetAtt EC2Instance.PublicIp
  RDSEndpoint:
    Description: RDS Connection Endpoint
    Value: !GetAtt RDSInstance.Endpoint.Address
  S3BucketName:
    Description: Name of S3 Bucket
    Value: !Ref S3Bucket
